### ISSUE TITLE
How do I use Robber?

### ISSUE THREAD

**Issue by neox123** [MojtabaTajik/Robber#5]
Hi.

How do I specify the scan folder?

My OS : windows7 32bit

![err](https://user-images.githubusercontent.com/30784121/48705789-87c82080-ec3d-11e8-9b05-ab4569b408e5.PNG)

Thanks.

**Comment by MojtabaTajik** [comment]
Hi,
The directory browsing dialog used in Robber is standard component.
It seems the problem occurred because of your classic skin of Windows. please choose another skin for your OS and test again

**Comment by MojtabaTajik** [comment]
Hi,
The directory browsing dialog used in Robber is standard component.
It seems the problem occurred because of your classic skin of Windows. please choose another skin for your OS and test again
